[package]
name = "greycat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image2 = "1.9.2"
# Required because the latest version wants a newer rustc version
half = "= 2.2.1"
